In [1]:
import zipfile
import os
!wget https://github.com/RAlwean/Renaldi-Alwean-Saputra_2411532003_ML2526/raw/main/Praktikum5/titanic.zip

with zipfile.ZipFile('titanic.zip', 'r') as zip_ref:
    zip_ref.extractall('titanic_data')

print("File dalam folder:", os.listdir('titanic_data'))

--2026-05-05 14:15:51--  https://github.com/RAlwean/Renaldi-Alwean-Saputra_2411532003_ML2526/raw/main/Praktikum5/titanic.zip
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/RAlwean/Renaldi-Alwean-Saputra_2411532003_ML2526/main/Praktikum5/titanic.zip [following]
--2026-05-05 14:15:51--  https://raw.githubusercontent.com/RAlwean/Renaldi-Alwean-Saputra_2411532003_ML2526/main/Praktikum5/titanic.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34877 (34K) [application/zip]
Saving to: ‘titanic.zip’

titanic.zip         100%[===================>]  34.06K  --.-KB/s    in 0.003s

2026-05-05 14:15:51 (10.5 MB/s) - ‘titanic.zip’ saved [34877/34877]

File dalam folder: ['train.csv', 'gender_submission.csv', 'test.csv']

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('titanic_data/train.csv')
print("5 Data Teratas:")
df.head()

5 Data Teratas:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df = df.drop(['Name', 'Ticket', 'Cabin', 'PassengerId'], axis=1)

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

X_titanic = df.drop('Survived', axis=1)
y_titanic = df['Survived']

print("Data setelah praproses:")
X_titanic.head()

Data setelah praproses:

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2

In [5]:
model_titanic = LogisticRegression(max_iter=1000)

kf_titanic = KFold(n_splits=5, shuffle=True, random_state=42)

acc_scores = cross_val_score(model_titanic, X_titanic, y_titanic, cv=kf_titanic, scoring='accuracy')

print("=== Analisis Kinerja Model (Titanic) ===")
print(f"Akurasi tiap fold: {acc_scores}")
print(f"Rata-rata Akurasi: {acc_scores.mean():.4f}")
print(f"Standar Deviasi (Variasi): {acc_scores.std():.4f}")

=== Analisis Kinerja Model (Titanic) ===
Akurasi tiap fold: [0.81005587 0.79213483 0.84269663 0.7752809  0.78651685]
Rata-rata Akurasi: 0.8013
Standar Deviasi (Variasi): 0.0235